name: pyupload
version: git
base: core18
summary: PyUpload
description: |
        A tool to manage uploading files to Auphonic and Archive.org

grade: devel
confinement: strict

apps:
        pyupoad:
                command: bin/pyupload
                plugs:
                        - removable-media
                        - network

parts:
        pyupload:
                plugin: python
                source: .
                python-packages:
                        - wheel
                        - requests
                        - internetarchive
